server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://8.129.213.16:3306/ry-vue?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
    database: 0
    host: 8.129.213.16
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

xxl:
  job:
    admin:
      addresses: http://8.129.213.16:8084/xxl-job-admin/
    accessToken:
    executor:
      appname: xxl-job-management
      address:
      ip:
      port: 10001
      logretentiondays: 30
      logpath: /applogs/xxl-job/jobhandler

jwt:
  tokenHeader: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expiration: 604800
  tokenHead: Bearer
secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /login
      - /register
      - /logout
      - /captchaImage
      - /*.html
      - /**/*.html
      - /webjars/**
      - /*/api-docs


sxysibe:
    gds:
        amadeus:
            app-key: test
            search-url: http://localhost:9091
#            verify-url: http://localhost:9091
#            order-url: http://localhost:9091
            contact:
                name: A1IncLtd
                address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
                mobile: SZX 86-18948735931-HONG KONG NG CHOW INTERNATIONAL TRAVEL
                ctct: 8618948735931
        galileo:
            app-key: test
            search-url: http://localhost:9092
#            verify-url: http://localhost:9092
#            order-url: http://localhost:9092
            contact:
                name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
                address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
                mobile: 852-31055092
                ctct: 8618948735931
