server:
  port: 8085

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://106.75.115.170:8090/eureka/
#      defaultZone: http://192.168.1.101:8090/eureka/

spring:
  application:
    name: management-client #服务名称--调用的时候根据名称来调用该服务的方法

  datasource:
    url: jdbc:mysql://106.75.115.170:3306/ry-vue?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 80
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
    database: 0
    host: 106.75.115.170
    port: 6379

    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 300
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 100
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 50
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

xxl:
  job:
    admin:
      addresses: http://106.75.115.170:8092/xxl-job-admin/
#      addresses: http://192.168.1.101:8092/xxl-job-admin/
    accessToken:
    executor:
      appname: xxl-job-management
      address:
      ip:
      port: 10001
      logretentiondays: 30
      logpath: /applogs/xxl-job/jobhandler

jwt:
  tokenHeader: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expiration: 604800
  tokenHead: Bearer
secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /login
      - /register
      - /logout
      - /captchaImage
      - /*.html
      - /**/*.html
      - /webjars/**
      - /*/api-docs


sxysibe:
    compass:
       switchgds: false
       compresstype: GZIP
    redis:
      #刷新缓存开关，是否开机刷新缓存
      refresh-switch: false
      #是否将gds数据缓存至redis
      refresh-gds-switch: true
      #是否刷新其它站点数据至redis
      refresh-other-site-switch: true
      #刷新其它站点相关列表配置 OTA平台代码-站点代码 如： CTRIP-CT001
      refresh-ota-sites: CTRIP-CT001,CTRIP-CT002
    ota:
      #加密datakey ##Data Key
      data-key: 6784397598743236
      #OTA平台
      #站点
      ota: CTRIP
      site:
      #cid 可以理解为：app key 身份识别
      cid:
      #日志
      logger-path: /var/log/sibe
      #日志文件是否保存本地
      logger-save-file-flag: true
      #1.没有匹配上政策，或者没有政策录入其他说明， 则返回此信息 Rule Element 其他说明： 注意@@仅仅是区分 直接政策投放，还是手功政策投放
      other-issue-ticket-msg: 只提供国际报销凭证（香港INVOICE）,所有退票改期必须提前48小时申请，否则视为误机,误机后不得退票。退改业务请在工作时间（周一至周五09:00~17:30）联系我们。友情提示：机票须按航班起飞时间顺序使用，否则无法登机。本公司只是机票代理，签证问题请自行确认，保证24小时以内出票。@@

      #数据接收方OTA平台站点的缓存时间，单位秒
      ota-site-cache-time: 600
    gds:
        fuse-time: 20
        amadeus:
            app-key: test
            search-url: http://106.75.115.170:9091
#            search-url: http://localhost:9091
#            verify-url: http://localhost:9091
#            order-url: http://localhost:9091
            contact:
                name: A1IncLtd
                address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
                mobile: SZX 86-18948735931-HONG KONG NG CHOW INTERNATIONAL TRAVEL
                ctct: 8618948735931
        galileo:
            app-key: test
            search-url: http://localhost:9092
#            verify-url: http://localhost:9092
#            order-url: http://localhost:9092
            contact:
                name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
                address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
                mobile: 852-31055092
                ctct: 8618948735931
        nh:
          app-key: test
          search-url: http://106.75.115.170:8086
#          search-url: http://192.168.1.101:8086
          other-url: http://192.168.3.221:19091
          contact:
            name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
            address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
            mobile: 852-31055092
            ctct: 8618948735931
            email: MT.sxycsh@cywz.cn
        cq:
          app-key: test
          search-url: http://106.75.115.170:8086
#          search-url: http://192.168.1.101:8086
          other-url: http://192.168.3.221:19091
          contact:
            name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
            address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
            mobile: 852-31055092
            ctct: 8618948735931
            email: MT.sxycsh@cywz.cn
        aq:
          app-key: test
          search-url: http://106.75.115.170:8086
#          search-url: http://192.168.1.101:8086
          other-url: http://192.168.3.221:19091
          contact:
            name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
            address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
            mobile: 852-31055092
            ctct: 8618948735931
            email: MT.sxycsh@cywz.cn
